# mod 'stdlib',
#   :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'
