name 'with-puppetfile-and-modulefile'
version '0.0.1'

author 'librarian'
license 'Apache License, Version 2.0'

dependency 'maestrodev/test'
dependency 'puppetlabs/stdlib', '3.2.1'
dependency 'puppetlabs/concat', '<=1.0.2'
