forge 'http://forge.puppetlabs.com'

mod 'maestrodev/test', :git => "https://github.com/maestrodev/puppet-test.git", :ref => "v1.0.8"
mod 'puppetlabs/stdlib', '>=4.0.0'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat', '<=1.0.2'
